#pragma once

#define MEDIA_PATH "D:\\Media\\"

#define COLOR_SIDE_PANEL    0x20D81B60

#define COLOR_BG            0xFF212121
#define COLOR_WHITE         0xFFFFFFFF
#define COLOR_TEXT_GRAY     0xFFB0B0B0
#define COLOR_PRIMARY       0xFFDF4088
#define COLOR_SECONDARY     0xFF424242
#define COLOR_CARD_BG       0xFF303030
#define COLOR_CARD_SEL      0xFF4A4A4A
#define COLOR_SUCCESS       0xFF4CAF50
#define COLOR_DOWNLOAD      0xFF2196F3

#define CARD_GAP            16.0f

#define STORE_GRID_COLS         5
#define STORE_GRID_ROWS         2
#define STORE_ITEMS_PER_SCREEN  (STORE_GRID_COLS * STORE_GRID_ROWS)
#define STORE_API_PAGE_SIZE     20
#define STORE_CHUNK_SIZE        (STORE_ITEMS_PER_SCREEN * 3)
#define STORE_MAX_ICONS_IN_RAM  10
#define STORE_CACHE_FILE_LIMIT  100

#define ASSET_HEADER_HEIGHT 56
#define ASSET_SIDEBAR_Y 76
#define ASSET_SIDEBAR_WIDTH 172
#define ASSET_SIDEBAR_HIGHLIGHT_WIDTH 192
#define ASSET_SIDEBAR_HIGHLIGHT_HEIGHT 84
#define ASSET_CATEGORY_ICON_WIDTH 24
#define ASSET_CATEGORY_ICON_HEIGHT 24
#define ASSET_CONTROLLER_ICON_WIDTH 24
#define ASSET_CONTROLLER_ICON_HEIGHT 24
#define ASSET_STORE_ICON_WIDTH 32
#define ASSET_STORE_ICON_HEIGHT 32
#define ASSET_FOOTER_HEIGHT 46