#pragma once

#include <xtl.h>
#include <xgraphics.h>
#include <d3dx8.h>
#include <stdint.h>
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <tchar.h>
#include <time.h>
#include <cassert>
#include <cctype>
#include <cstdio>
#include <curl/curl.h>
#include <winsockx.h>
#include <deque>
#include <map>
#include <string>
#include <utility>
#include <vector>
#include <algorithm>
#include <cstring>
#include <ctime>
#include <io.h>